all: bill ksmallqs logn2 nrootn

bill:
	g++ src/billgates_inplace.cpp -o billgates_inplace

ksmallqs:
	g++ src/ksmallestusingqs.cpp -o ksmallestusingQS

logn2:
	g++ src/logn2.cpp -o logn2

nrootn:
	g++ src/nrootn.cpp -o nrootn